### ISSUE TITLE
Throwing error with specific link

### ISSUE THREAD

**Issue by feedm3** [feedm3/hypem-resolver#3]
hypem-resolver throws an error with the following link
http://hypem.com/serve/source/2ey1t/a5ef420f37c737e9883d287cd1805055

the hypem-resolver should never throw an error and only pass an error object to the callback

``` javascript
Error: Nothing found: http://hypem.com/serve/source/2ey1t/a5ef420f37c737e9883d287cd1805055
    at Request._callback (C:\Users\###\###\###\node_modules\hypem-resolver\hypem-resolver.js:152:26)
    at Request.self.callback (C:\Users\###\###\###\node_modules\request\request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (C:\Users\###\###\###\node_modules\request\request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (C:\Users\###\###\###\node_modules\request\request.js:962:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at nextTickCallbackWith2Args (node.js:478:9)
    at process._tickCallback (node.js:392:17)
```

**Comment by feedm3** [comment]
It seems that the error was thrown by a parent module. I added test for this URL to verify that no error is thrown.

Commit https://github.com/feedm3/hypem-resolver/commit/759da53740c63df97d65cb2a7b3f7856d4fc71fe
